# Generated by Django 5.0.3 on 2024-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
